version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4040:4040"
    restart: always
    environment:
      - NODE_ENV=production

  # Для разработки
  frontend_dev:
    image: node:18-alpine
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    profiles:
      - dev
