import { Season } from "../../models/enums"

// Тестовые данные для отображения на главной странице
export const mockTours = [
  {
    id: 1,
    name: "Солнечный Сочи",
    description:
      "Отличный летний отдых на побережье Черного моря. Комфортабельные отели, чистые пляжи и множество развлечений для всей семьи.",
    country: "Россия",
    season: Season.SUMMER,
    type: "Пляжный",
    imagePath: "https://images.unsplash.com/photo-1605535786324-311a4b4b0a39",
    startDate: "2023-07-15",
    endDate: "2023-07-25",
    duration: 10,
    totalSlots: 20,
    availableSlots: 8,
    isRegistrationClosed: false,
  },
  {
    id: 2,
    name: "Активный Алтай",
    description:
      "Пешие походы, сплавы по горным рекам и потрясающие пейзажи. Отдых для любителей активного образа жизни.",
    country: "Россия",
    season: Season.SUMMER,
    type: "Активный",
    imagePath: "https://images.unsplash.com/photo-1599056112624-2556686f4a32",
    startDate: "2023-08-05",
    endDate: "2023-08-15",
    duration: 10,
    totalSlots: 15,
    availableSlots: 3,
    isRegistrationClosed: false,
  },
  {
    id: 3,
    name: "Турецкая сказка",
    description:
      'Отдых по системе "все включено" в лучших отелях Антальи. Белоснежные пляжи, теплое море и богатая экскурсионная программа.',
    country: "Турция",
    season: Season.SUMMER,
    type: "Пляжный",
    imagePath: "https://images.unsplash.com/photo-1547634678-0a97468bcfc7",
    startDate: "2023-06-20",
    endDate: "2023-06-30",
    duration: 10,
    totalSlots: 30,
    availableSlots: 0,
    isRegistrationClosed: true,
  },
  {
    id: 4,
    name: "Горнолыжные Альпы",
    description:
      "Захватывающие спуски, современные подъемники и комфортабельные шале. Идеальный отдых для любителей зимних видов спорта.",
    country: "Австрия",
    season: Season.WINTER,
    type: "Активный",
    imagePath: "https://images.unsplash.com/photo-1520839608488-8b43c868301d",
    startDate: "2023-12-20",
    endDate: "2023-12-30",
    duration: 10,
    totalSlots: 20,
    availableSlots: 15,
    isRegistrationClosed: false,
  },
  {
    id: 5,
    name: "Египетские каникулы",
    description:
      "Фешенебельные отели, теплое Красное море и древние достопримечательности. Отдых, который подойдет для всей семьи.",
    country: "Египет",
    season: Season.AUTUMN,
    type: "Семейный",
    imagePath: "https://images.unsplash.com/photo-1584720223124-0d19d2a10b55",
    startDate: "2023-09-25",
    endDate: "2023-10-05",
    duration: 10,
    totalSlots: 25,
    availableSlots: 12,
    isRegistrationClosed: false,
  },
  {
    id: 6,
    name: "Тайские приключения",
    description:
      "Экзотические пляжи, тропические джунгли и богатая культура. Незабываемый отдых в одной из самых удивительных стран Азии.",
    country: "Таиланд",
    season: Season.WINTER,
    type: "Экзотический",
    imagePath: "https://images.unsplash.com/photo-1506665531195-3566af98b107",
    startDate: "2024-01-15",
    endDate: "2024-01-29",
    duration: 14,
    totalSlots: 18,
    availableSlots: 10,
    isRegistrationClosed: false,
  },
  {
    id: 7,
    name: "Весенняя Прага",
    description:
      "Средневековая архитектура, уютные кафе и богатая история. Идеальное направление для романтического отдыха.",
    country: "Чехия",
    season: Season.SPRING,
    type: "Экскурсионный",
    imagePath: "https://images.unsplash.com/photo-1541849546-216549ae216d",
    startDate: "2023-04-10",
    endDate: "2023-04-17",
    duration: 7,
    totalSlots: 20,
    availableSlots: 0,
    isRegistrationClosed: true,
  },
  {
    id: 8,
    name: "Райские Мальдивы",
    description:
      "Роскошные бунгало над водой, кристально чистые лагуны и коралловые рифы. Идеальное место для романтического отдыха.",
    country: "Мальдивы",
    season: Season.WINTER,
    type: "Пляжный",
    imagePath: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8",
    startDate: "2024-02-10",
    endDate: "2024-02-20",
    duration: 10,
    totalSlots: 15,
    availableSlots: 7,
    isRegistrationClosed: false,
  },
]
